/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.sql.*;
/**
 *
 * @author Moreno
 */
public class GUI2 extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        
        model = (DefaultTableModel)tblmhs.getModel();
        tblmhs.setModel(model);
        tampilData();
    }
    private void tampilData() {
        String nama,nim,prodi,notelp;
        try {
            Connection con = Koneksi.GetConnection();
            Statement st = con.createStatement();
            
            String query = "SELECT nama,nim,prodi,notelp FROM mahasiswa";
            ResultSet rs = st.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) tblmhs.getModel();
            model.setRowCount(0);
            
            while(rs.next()) {
                nama = rs.getString("nama");
                nim = rs.getString("nim");
                prodi = rs.getString("prodi");
                notelp = rs.getString("notelp");
                Object[] data = {nama,nim,prodi,notelp};
                model.addRow(data);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lnama = new javax.swing.JLabel();
        Lnim = new javax.swing.JLabel();
        Lprodi = new javax.swing.JLabel();
        Lnotelp = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFnim = new javax.swing.JTextField();
        TFprodi = new javax.swing.JTextField();
        TFnotelp = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btntampil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lnama.setText("Nama");

        Lnim.setText("NIM");

        Lprodi.setText("Prodi");

        Lnotelp.setText("No Telp");

        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });

        TFnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnimActionPerformed(evt);
            }
        });

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btntampil.setText("Tampil");
        btntampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilActionPerformed(evt);
            }
        });

        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Prodi", "No Telp"
            }
        ));
        jScrollPane1.setViewportView(tblmhs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnhapus)
                        .addGap(59, 59, 59)
                        .addComponent(btntampil)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnim)
                            .addComponent(Lprodi)
                            .addComponent(Lnama)
                            .addComponent(Lnotelp))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFnama, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(TFnim)
                            .addComponent(TFprodi)
                            .addComponent(TFnotelp))
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnama)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lnim))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lprodi))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lnotelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnhapus)
                    .addComponent(btntampil))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void TFnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnimActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String nama, nim, prodi, notelp;
        nama    = TFnama.getText();
        nim     = TFnim.getText();
        prodi   = TFprodi.getText();
        notelp  = TFnotelp.getText();
        Object[] data = {nama,nim,prodi,notelp};
        model.addRow(data);
        try {
            Connection con = Koneksi.GetConnection();
            String query = "INSERT INTO mahasiswa(nama,nim,prodi,notelp) VALUES(?,?,?,?)";
            PreparedStatement p = con.prepareStatement(query);
            
            p.setString(1,nama);
            p.setString(2,nim);
            p.setString(3,prodi);
            p.setString(4,notelp);
            
            p.executeUpdate();
            p.close();
            System.out.println("Executed");
            TFnama.setText("");
            TFnim.setText("");
            TFprodi.setText("");
            TFnotelp.setText("");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btntampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btntampilActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblmhs.getSelectedRow();
        if(selectedRowIndex == -1){
            JOptionPane.showMessageDialog(this, "Tidak ada tabel yang dipilih.");
        }
        else {
            String nim = tblmhs.getValueAt(selectedRowIndex, 1).toString();
            
            try {
                Connection con = Koneksi.GetConnection();
                String query = "DELETE FROM mahasiswa where nim = ?";
                PreparedStatement p = con.prepareStatement(query);
                p.setString(1,nim);
            
                p.executeUpdate();
                p.close();
                
                DefaultTableModel model = (DefaultTableModel) tblmhs.getModel();
                model.removeRow(selectedRowIndex);
                
                JOptionPane.showMessageDialog(this, "Tabel berhasil dihapus.");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus data");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**`
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lnim;
    private javax.swing.JLabel Lnotelp;
    private javax.swing.JLabel Lprodi;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFnim;
    private javax.swing.JTextField TFnotelp;
    private javax.swing.JTextField TFprodi;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntampil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmhs;
    // End of variables declaration//GEN-END:variables
}
